cloud:
  aws:
    credentials:
      access-key: AKIA54AWUPO3TCMGKHFK
      secret-key: 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
      region:
        static: us-central-1
        auto: false

application :
  bucket:
    name: soundcloudtalents

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50
      max-request-size: 100

server:
  port: 9999