cloud:
  aws:
    credentials:
      access-key: AKIA54AWUPO3V4RSIQNV
      secret-key: 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
      region:
        static: us-central-1
        auto: false

application :
  bucket:
    name: soundcloudtalents

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50
      max-request-size: 100

server:
  port: 9999


  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/soundcloud
      username: root
      password: javadeveloper94.
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.DB2Dialect