cloud:
  aws:
    credentials:
      access-key: AKIA54AWUPO3YS47GH54
      secret-key: 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
      region:
        static: us-central-1
        auto: false

application :
  bucket:
    name: soundcloudtalents

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50
      max-request-size: 100

server:
  port: 9999